name: Publish Version
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: twilioquest/twilioquest-base/.github/workflows/publish-version.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
